openapi: 3.0.3
info:
  title: "Phone Verification API"
  version: '1.0'
  contact:
    name: tyntec API Support
    url: https://www.tyntec.com/support
    email: support@tyntec.com
  x-repository: https://github.com/tyntec/api-collection/blob/master/verification
  x-specification-file: phoneVerification.yaml
  x-major-version: v1
servers:
  - url: https://api.tyntec.com/verification/v1
tags:
  - name: "Phone Verification"
    description: |
      Phone Verification service aims to determine validity, reachability and fraud risk of phone numbers entered into
      forms by users or auto dialers so that brands can ensure their customer records are accurate,
      improve conversion rates for customer outreach, and guard against bad actors.

      The API determines the reachability and trustworthiness of phone numbers through:

      - **Validity Check:** check if the phone number is valid according to the numbering plan for that country.
      - **Active Status:** check if the phone number has been assigned to a subscriber by an operator.
      - **Number Type:** determine the phone number type to decide which technology to use to communicate.
      - **Mobile Operator:** identify the name and the country of the home network operator for the subscriber.
      - **Outreach Status:** check if an SMS can be delivered to the subscriber behind the phone number.
      - **Fraud Risk:** determine the likelihood of the phone number being used by a bad actor.
  - name: Metadata
    description: |
      Metadata information regarding the API itself. The information exposed is:

      - **API Health:** Information regarding the status of the API.
      - **Version:** The version of the API and API specification.
security:
  - APIKeyHeader: []
paths:
  /phone/{number}:
    get:
      tags:
        - "Phone Verification"
      summary: Verify Number
      description: |
        Phone Verification is a web service that responds with information regarding the validity, reachability and trustworthiness of a phone number.
      operationId: phoneVerificationGET
      parameters:
        - name: number
          in: path
          required: true
          description: |
            The phone number to be verified, given in the international format
          schema:
            type: string
            example: +491621234567
      responses:
        200:
          description: A valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/numberResponse'
        401:
          description: Missing or Invalid API credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse401'
        403:
          description: Permission denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse403'
  /health:
    get:
      tags:
        - Metadata
      summary: Phone Verification API health
      description: Phone Verification health endpoint provides information about the status of the API
      operationId: getPhoneVerificationHealth
      responses:
        200:
          description: API is up and running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/healthResponse'
        403:
          description: Permission denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse403'
  /version:
    get:
      tags:
        - Metadata
      summary: Phone Verification API version
      description: Phone Verification version endpoint provides information about the current version of the Phone Verification API
      operationId: getVersion
      responses:
        200:
          description: The current API version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/versionResponse'
        403:
          description: Permission denied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse403'
components:
  schemas:
    numberResponse:
      type: object
      properties:
        validNumberFormat:
          type: string
          example: "true"
          description: Is the number formatted correctly according to the numbering plan? Possible values (true, false)
        activeNumber:
          type: string
          example: "true"
          description: Is the number currently assigned to a subscriber? Possible values (true, false, unknown)
        numberType:
          type: string
          example: "mobile"
          description: Type of the phone number. Possible values (fixed, mobile, fixed_or_mobile, mvno_gsm, iden, cdma, gsm_cdma, toll_free, premium_rate, shared_cost, voip, personal, pager, uan, voicemail, unknown)
        operatorName:
          type: string
          example: "T-Mobile Czech Republic a.s."
          description: Who is the home network operator of the subscriber?
        operatorCountry:
          type: string
          example: "CZE"
          description: In which country is the number registered? The country if formated in ISO3 code
        fraudRisk:
          type: string
          example: "low"
          description: What is the likelihood of the number being associated with fraud? Possible values (low, medium, high, unknown)
        outreachReady:
          type: string
          example: "true"
          description: Should a message be sent to this number? Possible values (true, false)
    healthResponse:
      type: object
      properties:
        status:
          type: string
          example: "up"
        updatedAt:
          type: integer
          example: 12321546464
          description: Timestamp
    versionResponse:
      type: object
      properties:
        version:
          type: string
          example: "v0"
        updatedAt:
          type: integer
          example: 12321546464
          description: Timestamp
    errorResponse401:
      type: object
      properties:
        error:
          type: string
          example: "No API key found in request"
          description: An error message of an unsuccessful request
    errorResponse403:
      type: object
      properties:
        error:
          type: string
          example: "Invalid authentication credentials"
          description: An error message of an unsuccessful request
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      name: apiKey
      in: header