openapi: '3.0.0'
info:
  title: Conversations API
  description: |
    The Conversations API allows you to easily send messages to your customers via messaging services like WhatsApp
    or Viber and still reach customers with classic SMS, with a harmonized data model over all channels.

    This API is designed for 2-way messaging (sending and receiving), which allows interactive conversations
    with your customers.

    Delivery notifications (message status updates) and inbound messages from your customers are sent by us to your
    system via the HTTP ```POST``` method. For details see [Receiving status updates](#receiving-status-updates) and
    [Receiving inbound messages](#receiving-inbound-messages).

    ## Channels

    The Conversations API provides messaging services via several channels, currently:

    - WhatsApp
    - Viber
    - 2-way SMS (sending and receiving)

    **Note:** If you want to send SMS only, check out our [SMS API](/sms/current.html), which is preferred for 1-way
    SMS messaging.

    **Channel specific prerequisites**

    - *WhatsApp:* A WhatsApp Business Account (WABA) is required in order to use this channel.<br>
      Please [request your access here](https://my.tyntec.com).
    - *Viber:* A Viber Service ID is required in order to use this channel.<br>
      Please [request your access here](https://my.tyntec.com).
    - *2-way SMS:* Please [contact us](/help.html) to get the details for the 2-way SMS setup.



    ## Scope based access control

    The Conversations API uses the concept of scopes to control access to different aspects of your Conversations account and
    channels available to you.

    Scopes are divided into two distinct classes `read` and  `write`.

    `read` grants you read-only access - `GET` HTTP calls -.

    `write` provides access to data modification or message submission - `POST`, `PATCH`, `PUT`, `DELETE` HTTP calls -.

    Scopes are used on 2 layers, your API key account and the channels available to it.

    You can inspect the scopes available to both layers by fetching the information via [Configurations](#configurations).

    We reserve the right to revoke any granted scope in case we do detect abusive usage of the API.

    ## Adhered web standards

    In addition to the [compliance common to all our APIs](/index.html#general-web-standards),
    the Conversations API complies also with:

    - [RFC 5988 – Web Linking](https://tools.ietf.org/html/rfc5988)

    *RFC 5988* is implemented to allow all API calls that return a list of resources, to make use of the following
    _Link_ headers:

    - `first` – The first page in the list of requested sub-resources
    - `previous` – The page preceding the current page in the list of requested sub-resources
    - `current` – The current page in the list of requested sub-resources
    - `next` – The page following the current page in the list of requested sub-resources
    - `last` – The last page in the list of requested sub-resources

    In addition, the following custom headers are provided for convenience:

    - `x-total-pages` – The total number of pages in the list of requested sub-resources
    - `x-total-items` – The total number of items in the list of requested sub-resources
    - `x-page-size` – The size of a page (maximum number of items on a single page)
    - `x-current-page` – The page number of the current page in the list of requested sub-resources

  contact:
    name: tyntec API Support
    url: http://www.tyntec.com/support
    email: support@tyntec.com
  version: '3.24'
  x-repository: https://github.com/tyntec/api-collection/blob/master/conversations
  x-major-version: v3
  x-postman-collection: postman.zip
  x-master-file: true

paths: {}
