openapi: '3.0.0'
info:
  title: SMS
  description: |
    Conversations allows you to easily reach out and communicate with your clients via 2-way SMS.

    **Channel specific pre-conditions**

    - *2-way SMS* : Please contact us to get the details for the 2-way SMS setup
  contact:
    name: tyntec API Support
    url: http://www.tyntec.com/support
    email: support@tyntec.com
  version: '3.0'
  x-repository: https://github.com/tyntec/api-collection/blob/master/conversations
  x-specification-file: sms.yaml
  x-major-version: v3
servers:
  - url: https://api.tyntec.com/conversations/v3
security:
  - ApiKeyAuth: [ ]
paths:
  /messages:
    post:
      operationId: sendMessage
      summary: Send a message
      tags:
        - "Messaging"
      description: Send messages via this path.
      requestBody:
        description: The message you would like to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        202:
          $ref: '#/components/responses/MessageResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /bulks:
    post:
      operationId: sendABulkMessage
      summary: Send a bulk message
      tags:
        - "Messaging"
      description: Send bulk messages. Bulk messages are defined as ordered messages to **one** receiver.
      requestBody:
        description: The message bulk you would like to send
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkMessageRequest'
      responses:
        202:
          $ref: '#/components/responses/BulkMessageResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /configurations/channels/sms:
    get:
      tags:
        - "Inbound Phone Numbers"
      summary: List Phone Numbers
      operationId: listAllSMSChannels
      description: List all Inbound SMS channels available to your API account
      responses:
        200:
          $ref: '#/components/responses/ListAllSMSChannelsResponse'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /configurations/channels/sms/phone-numbers/{phone-number}:
    parameters:
      - $ref: '#/components/parameters/PhoneNumber'
    get:
      tags:
        - "Inbound Phone Numbers"
      summary: Read a configuration
      operationId: getSMSChannelConfig
      description: Returns the specific inbound configuration
      responses:
        200:
          $ref: '#/components/responses/SMSChannelResponse'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
  /configurations/channels/sms/phone-numbers/{phone-number}/callbacks:
    parameters:
      - $ref: '#/components/parameters/PhoneNumber'
    put:
      tags:
        - "Callback configuration"
      summary: Update the callback
      operationId: updateSMSChannelCallback
      description: Update the callback settings of a specific inbound sms. **Note** The complete object must be provided
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChannelCallback'
      responses:
        200:
          $ref: '#/components/responses/SMSChannelResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        403:
          $ref: '#/components/responses/Forbidden'
        default:
          $ref: '#/components/responses/Default'
components:
  parameters:
    PhoneNumber:
      name: phone-number
      in: path
      required: true
      description: Phone number used for WhatsApp messaging.
      schema:
        type: integer
        minLength: 4
        maxLength: 15
      example: 4923147790717
  responses:
    MessageResponse:
      description: Response after the server has accepted the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MessageResponse'
    BulkMessageResponse:
      description: Response after the server has accepted the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BulkMessageResponse'
    Default:
      description: Default response in case of any other error. Please check the error object for details
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    BadRequest:
      description: The request does not match our expectations. Please check the Problems object for details
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            status: 400
            violations: [
              {
                field: validate.request.content.contentType,
                message: must not be empty
              }
            ]
            title: Constraint Violation
    Forbidden:
      description: You attempting to use a number that is not assigned to your account
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            type: https://httpstatuses.com/403
            title: Forbidden
            status: 403
    ListAllSMSChannelsResponse:
      description: A list of SMS channel configurations
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SMSChannelResponses'
    SMSChannelResponse:
      description: A list of SMS channel configurations
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SMSChannelResponse'
  schemas:
    Problem:
      $ref: './common.yaml#/components/schemas/Problem'
    MessageResponse:
      $ref: './common.yaml#/components/schemas/MessageResponse'
    BulkMessageResponse:
      $ref: './common.yaml#/components/schemas/BulkMessageResponse'
    MessageRequest:
      type: object
      description: The message you would like to send
      required:
        - to
        - channel
        - from
      properties:
        to:
          type: string
          description: |
            The receipient of the messages
            The format depends on the specific channel
          example: "+1233423454"
        from:
          type: string
          description: |
            The sender of the messages. The format depends on the specific channel.
          example: "+1233423454"
        channel:
          type: string
          description: Channel selected for delivery.
          example: sms
          items:
            type: string
            enum:
              - sms
        overrides:
          $ref: 'common.yaml#/components/schemas/MessageRequestOverrides'
        context:
          type: string
          description: Context for this particular message
          maxLength: 125
        content:
          $ref: '#/components/schemas/SMSContent'
      example:
        to: "+123234234"
        from: "545345345"
        channel:  "sms"
        content:
          contentType: text
          text: A simple text message
    BulkMessageRequest:
      type: object
      description: The bulk of messages you would like to send
      required:
        - to
        - channel
        - from
        - messages
      properties:
        to:
          type: string
          description: |
            The receipient of the messages
            The format depends on the specific channel
          example: "+1233423454"
        from:
          type: string
          description: |
            The sender of the messages. The format depends on the specific channel.
          example: "+1233423454"
        channel:
          type: string
          description: Channel selected for delivery.
          example: sms
          items:
            type: string
            enum:
              - sms
        messages:
          type: array
          maxItems: 20
          minItems: 2
          items:
            $ref: '#/components/schemas/SMSContent'
    SMSContent:
      type: object
      properties:
        contentType:
          type: string
          enum:
            - text
          default: text
        text:
          type: string
          maxLength: 3000
    SMSChannelResponse:
      $ref: './configurations.yaml#/components/schemas/SMSChannelResponse'
    SMSChannelResponses:
      $ref: './configurations.yaml#/components/schemas/SMSChannelResponses'
    ChannelCallback:
      $ref: './configurations.yaml#/components/schemas/ChannelCallback'