openapi: 3.0.0
info:
  title: Mobile Inbound SMS API
  description: |
    The Mobile Inbound SMS API enables you to receive messages from your
    customers sent to phone numbers you have registered with Tyntec.

    For this service you will need to provide tyntec with the URL
    (`callbackUrl`) of your webserver, e.g.
    `https://rest.customer.com/inboundmessages/`.

    tyntec's application will do either a `POST` or `GET` call to you
    server; this can be configured by tyntec.

    tyntec's application will retry delivery every 10 seconds in case your
    application does not accept the inbound message. Retries are paused for
    10 minutes after every 100 consecutive unsuccessful delivery attempts.
    tyntec's application will retry for a maximum of 48 hours.

  contact:
    name: tyntec API Support
    url: http://www.tyntec.com/support
    email: support@tyntec.com
  version: '1.0'
  x-repository: https://github.com/tyntec/api-collection/blob/master/mobile-inboud-api
  x-major-version: v1
paths:
components:
  schemas:
    InboundMessage:
      title: InboundMessage
      required:
        - from
        - to
        - message
        - requestId
        - missingParts
        - contentList
      type: object
      properties:
        from:
          type: string
          description: The phone number of the sending party in international format if available.
          example: '+49123456789'
        to:
          type: string
          description: Your number provided by tyntec that has received the respective message in international format.
          example: '+1987654321'
        message:
          type: string
          description: 'The received message as an UTF-8 encoded string. Note: Missing parts of a concat message will be marked with <...> in the message'
          example: 'This is an example, the data is garbage'
        originMCC:
          type: string
          description: A representative MCC (Mobile Country Code) of the originating network.
          example: 260
        originMNC:
          type: string
          description: A representative MNC (Mobile Network Code) of the originating network.
          example: 09
        originTtId:
          type: string
          description: The tyntec id of the operator.
          example: 77292
        totalPrice:
          type: number
          description: The sum of prices for each message part listed in “contentList”.
          example: -0.005
        requestId:
          type: string
          description: The unique identifier provided for each request.
          example: "e74db8d4-77ad-4671-8feb-9bc76b0df188"
        size:
          type: integer
          description: The amount of respective concatenated SMS parts.
          format: int32
          example: 1
        missingParts:
          type: boolean
          description: This flag marks if tyntec has received all parts of a concat message within a time limit of 10 minutes
          example: false
        contentList:
          type: array
          items:
            $ref: '#/components/schemas/content'
          description: 'tyntec merges over-length (concatenated) SMS into one string before sending it to your webserver. Note: tyntec will charge for each part of the concatenated message as an individual message!'
    content:
      title: content
      required:
        - msgId
        - sentDate
        - sequenceNumber
      type: object
      properties:
        msgId:
          type: string
          description: The unique identifier provided for each message part.
          example: '48799399408:0:cad578e86b324c0a80f8fe866bfdb2b6'
        sentDate:
          type: string
          description: >-
            The time when the SMS has been received by the sending MSC
            (if available)
            or
            the time when the respective message was received by tyntec.
          example: '2019-07-02T16:47:39+0200'
        sequenceNumber:
          type: integer
          description: The sequenceNumber orders the respective message parts of an overlength message.
          format: int32
          example: 1
        price:
          type: number
          description: The price per message from the respective network. Negative prices represent payout in favor of tyntec’s customer.
          example: -0.005
        currency:
          type: string
          description: The currency in which the pricing is given; corresponding to the currency of the invoice.
          example: EUR
        priceEffective:
          type: string
          description: The date when the “price” became effective.
          example: '2018-06-01T00:00:00+0200'
tags: []
