openapi: 3.0.1
info:
  contact:
    email: support@tyntec.com
    name: tyntec Support
    url: http://www.tyntec.com/support
  title: Callback Events
  version: 4
servers:
- description: Tyntec Server
  url: "Customer defined URL for receiving information events"
tags:
- description: |
    Webhooks is a way for an 2FA application to provide real-time information events.
    Tyntec sends a webhook to your application to notify you when an event occurs in your account.
    For example, Tyntec sends a webhook when an OTP is dispatched or when an OTP is delivered.
    You can use webhooks to trigger actions in your application or store data in your database.
    
    For configuring a webhook/callback please see 
    [Webhook Configuration](https://api.tyntec.com/reference/authentication/current.html?
                            urls.primaryName=configurations#configuration-management-api-Create%20Callback%20Configuration)
  name: Webhooks
paths:
  /:
    post:
      description: |
        Sends OTP events to the callback URL registered.
        
        - DISPATCHED
        - DELIVERED
        - UNDELIVERABLE
        - TIMED_OUT

        For details on error handling, you can refer to the following documentation pages:
        
        - **WhatsApp**
          
          - [On-Premises Errors](https://developers.facebook.com/docs/whatsapp/on-premises/errors)
          - [Cloud API Error Codes](https://developers.facebook.com/docs/whatsapp/cloud-api/support/error-codes)
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryStatus'
        description: Status of the OTP
        required: true
      responses:
        "200":
          description: OK
      summary: Send OTP event
      tags:
      - Webhooks
components:
  schemas:
    DeliveryStatus:
      type: object
      properties:
        channel:
          type: string
          enum:
          - SMS
          - VOICE
          - VIBER
          - WHATSAPP
        error:
          $ref: '#/components/schemas/Error'
        otpId:
          type: string
          format: uuid
          description: Unique identifier of the OTP
          example: a4762c77-94cb-43d6-bbab-9f37e088ad11
          title: OTP ID
        status:
          type: string
          description: status of the OTP Delivery
          enum:
          - RECEIVED
          - DISPATCHED
          - TIMED_OUT
          - DELIVERED
          - UNDELIVERABLE
          example: UNDELIVERABLE
          title: status
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the OTP event
          example: 2023-11-15T03:00:00Z
          title: Timestamp
    Error:
      type: object
      properties:
        code:
          type: string
          description: Error code
          example: tyntec::internal::500
          title: Error Code
        message:
          type: string
          description: Error message
          example: Internal Server Error
          title: Error Message
      title: Error
  securitySchemes:
    apiKey:
      in: header
      name: apiKey
      type: apiKey